version: '3'

services:
  nginx: #服务名称
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html  #挂载：前面是挂载到哪儿，后面是nginx得配置目录
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true   #解决nginx得文件调用权限的问题
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

